<a href="https://colab.research.google.com/github/amritjha123/Demo2/blob/main/Tensor_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


In [ ]:
scalar =torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
vector =torch.tensor([7,7])

In [ ]:
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
MATRIX = torch.tensor([[8,7],[8,3]])

In [ ]:
MATRIX

tensor([[8, 7],
        [8, 3]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([8, 7])

In [ ]:
MATRIX[1]

tensor([8, 3])

In [ ]:
MATRIX[-1]

tensor([8, 3])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
TENSOR = torch.tensor([[[1,2],
                        [2,4]],
                        [[1,6],
                         [5,9]]])

In [ ]:
TENSOR

tensor([[[1, 2],
         [2, 4]],

        [[1, 6],
         [5, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR[1]

tensor([[1, 6],
        [5, 9]])

In [ ]:
TENSOR[1][1]

tensor([5, 9])

In [ ]:
TENSOR[0][1][0]

tensor(2)

In [ ]:
TENSOR[0][1][1].item()

4

In [ ]:
TENSOR.shape

torch.Size([2, 2, 2])

In [ ]:
random_tensor = torch.rand(3,4)

In [ ]:
random_tensor

tensor([[0.6148, 0.9806, 0.6949, 0.4096],
        [0.6116, 0.3846, 0.4263, 0.2591],
        [0.2852, 0.5750, 0.6170, 0.5920]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_image_tensor = torch.rand(size = (3,224,224))
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [ ]:
zeros = torch.zeros(3,4)

In [ ]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(3,5)

In [ ]:
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
torch.arange(start = 4, end = 9, step = 0.6)

tensor([4.0000, 4.6000, 5.2000, 5.8000, 6.4000, 7.0000, 7.6000, 8.2000, 8.8000])

In [ ]:
one_to_ten = torch.arange(1,11)

In [ ]:
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ten_zeroes = torch.zeros_like(input = one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None,
                               device = None,
                               requires_grad= False)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [ ]:
float_16_tensor.dtype

torch.float16

 1. tensors not right datatype - to do get datatype from a tensor, can use tensor.dtype
    2. tensors not right shape - to get shape from atensor, can use tensor.ShapeType
    3. tensors not on the right device - to get device from atensor, can use tensor.device


In [ ]:
some_tensor = torch.rand(3,4, dtype= torch.float16)
some_tensor

tensor([[0.3486, 0.3892, 0.1401, 0.8594],
        [0.3701, 0.2021, 0.9541, 0.5459],
        [0.6885, 0.9399, 0.2769, 0.9922]], dtype=torch.float16)

In [ ]:
print(some_tensor)
print(f"datatype of tensor: {some_tensor.dtype}")
print(f"tensor size: {some_tensor.shape}")
print(f"device tensor is on: {some_tensor.device}")

tensor([[0.3486, 0.3892, 0.1401, 0.8594],
        [0.3701, 0.2021, 0.9541, 0.5459],
        [0.6885, 0.9399, 0.2769, 0.9922]], dtype=torch.float16)
datatype of tensor: torch.float16
tensor size: torch.Size([3, 4])
device tensor is on: cpu


In [ ]:
### Tensor operations: addition, subtraction, multiplication(element-wise), division, matrix multiplication

In [ ]:
tensor = torch.tensor([1,2,3])

In [ ]:
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor - 5

tensor([-4, -3, -2])

In [ ]:
tensor*7

tensor([ 7, 14, 21])

In [ ]:
tensor_div = tensor/2

In [ ]:
tensor.dtype, tensor_div.dtype

(torch.int64, torch.float32)

In [ ]:
torch.mul(tensor, 5)

tensor([ 5, 10, 15])

In [ ]:
torch.add(tensor, 8)

tensor([ 9, 10, 11])

In [ ]:
### Matrix multiplication is also known as dot product